# Generated by Django 2.2 on 2021-01-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('profile_pic', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=6)),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField()),
                ('note', models.TextField()),
                ('departments', models.ManyToManyField(to='employees.Department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
